// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwDlknBQXNX3qYFVaBXxjHMtBOwWt3lWQ',
    appId: '1:649076625943:web:4ccf7dedf40535b3760252',
    messagingSenderId: '649076625943',
    projectId: 'mymovieapp-ee342',
    authDomain: 'mymovieapp-ee342.firebaseapp.com',
    databaseURL: 'https://mymovieapp-ee342-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mymovieapp-ee342.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3t0uJx7TpyqBwZTKoTKyx2kjCE2Btuxo',
    appId: '1:649076625943:android:412cb97225356325760252',
    messagingSenderId: '649076625943',
    projectId: 'mymovieapp-ee342',
    databaseURL: 'https://mymovieapp-ee342-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mymovieapp-ee342.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAayZwwrudfaymWtzpp-ocrc4sUjnQ_rtI',
    appId: '1:649076625943:ios:cf5910e150175397760252',
    messagingSenderId: '649076625943',
    projectId: 'mymovieapp-ee342',
    databaseURL: 'https://mymovieapp-ee342-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mymovieapp-ee342.appspot.com',
    iosClientId: '649076625943-ho55fjj4jbcpuo4ksaliejbr2d206dr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMovieApp',
  );
}
