import 'dart:convert';

import 'package:dio/dio.dart';
import 'package:my_movie_app/model/collection_model.dart';
import 'package:my_movie_app/model/input_search_model.dart';
import 'package:http/http.dart' as http;
import 'dart:developer';

abstract class Search {
  Future searchMovie();
  Future searchCollections(String search);
  Future trendingMovies();
  Future topRated();
  // Future getLatest();
}

class SearchAll implements Search {
  String apiKey = '8fd9f7da67f9c8edcf2637b4d564d199';
  @override
  Future searchMovie() async {
    try {
      // final Dio dio = Dio();
      final response = await http.get(Uri.parse(
          'https://api.themoviedb.org/3/search/movie?api_key=$apiKey&language=en-US&query=Avengers&page=1&include_adult=false'));
      final movieCollection = jsonDecode(response.body);

      return MovieModel.fromJson(movieCollection);
    } catch (e) {
      log(e.toString());
    }
  }

  @override
  Future searchCollections(String search) async {
    try {
      final response = await http.get(Uri.parse(
          'https://api.themoviedb.org/3/search/collection?api_key=$apiKey&language=en-US&query=$search&page=1'));
      final movieCollection = jsonDecode(response.body);
      return Autogenerated.fromJson(movieCollection);
    } catch (e) {
      log(e.toString());
    }
  }

  @override
  Future trendingMovies() async {
    try {
      final response = await http.get(Uri.parse(
          'https://api.themoviedb.org/3/trending/all/day?api_key=$apiKey'));
      final trendingCollection = jsonDecode(response.body);
      return MovieModel.fromJson(trendingCollection);
    } catch (e) {
      log(e.toString());
    }
  }

  @override
  Future topRated() async {
    try {
      final response = await http.get(Uri.parse(
          'https://api.themoviedb.org/3/movie/top_rated?api_key=$apiKey&language=en-US&page=1'));
      final trendingCollection = jsonDecode(response.body);
      return MovieModel.fromJson(trendingCollection);
    } catch (e) {
      log(e.toString());
    }
  }
  // @override
  // Future getLatest() async{
  //   try {
  //     final response = await http.get(Uri.parse(
  //         'https://api.themoviedb.org/3/movie/latest?api_key=$apiKey&language=en-US'));
  //     final latestCollection = jsonDecode(response.body);
  //     return  Autogenerated.fromJson(latestCollection);
  //   } catch (e) {
  //     log(e.toString());
  //   }
  // }
}
